import DS from 'ember-data';
const { Model } = DS;

export default Model.extend({
    age: DS.attr('string'),
    adoptionStatus: DS.attr('string'),
    current_location_zip: DS.attr('string'),
    date_aquired: DS.attr('date'),
    date_of_birth: DS.attr('date'),
    default_image_id: DS.attr('number'),
    description: DS.attr(),
    goodWithBigDogs: DS.attr('string'),
    goodWithSmallDogs: DS.attr('string'),
    goodWithCats: DS.attr('string'),
    goodWithKids: DS.attr('string'),
    has_special_need: DS.attr('string'),
    images: DS.hasMany('image', { async: false }),
    is_housebroken: DS.attr('string'),
    is_spayed: DS.attr('string'),
    last_update: null,
    name: DS.attr('string'),
    numerical_age: DS.attr('string'),
    pet_adoption_url: DS.attr('string'),
    pet_attributes: DS.hasMany('pet-attribute', { async: false }),
    pet_foster_url: DS.attr('string'),
    pet_image: DS.attr('string'),
    public_url: DS.attr('string'),
    sex: DS.attr('string'),
    shots_up_to_date: DS.attr('string'),
    special_needs: DS.attr('string'),
    status: DS.attr('string'),
    temperament: DS.attr('string'),
    updated_at: DS.attr('string'),
    url_id: DS.attr('string'),
    weight: DS.attr('string'),
    youtube_url: DS.attr('string'),
    //youtube_urls: DS.hasMany('youtube-url', { async: false })
});
